/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeHandler */

#ifndef _Included_NativeHandler
#define _Included_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeHandler
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeHandler_start
  (JNIEnv *, jobject);

/*
 * Class:     NativeHandler
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeHandler_stop
  (JNIEnv *, jobject);

/*
 * Class:     NativeHandler
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeHandler_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
