/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sqlite.swig;

public class SWIGTYPE_p_p_Mem {
  private long swigCPtr;

  protected SWIGTYPE_p_p_Mem(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_Mem() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_Mem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

